//
// WARNING
//
// Do not make manual changes to this file.
// This file was generated by generate-AllBusinessIcons-component.js.
//
//


import React from 'react';

/**
 * A list of all available icons in the icon set.
 */
export type IconDefinition = 'logo';

export const availableIcons: IconDefinition[] = ['logo'];

export const IconSvg = {
  'logo': <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 105.77 26.426"><g fill="#e6101a" data-name="Group 9"><path d="M0 26.344h14.955l13.233-12.607a11.562 11.562 0 018.188-3.646h40.67L87.225.028h-50.71S27.77-.342 22.496 4.47 0 26.344 0 26.344z" data-name="Path 10"/><path d="M17.646 26.345h13.845l3.855-3.8a7.4 7.4 0 014.79-1.883h26.2l9.257-9.227h-37.26s-4.954-.21-7.942 2.516-12.745 12.394-12.745 12.394z" data-name="Path 11"/><path d="M79.516 26.322H63.137L89.392 0h16.374z" data-name="Path 12"/><g data-name="Group 8"><path d="M87.262 26.426v-2.658h-.994v-.541h2.66v.541h-.992v2.658z" data-name="Path 13"/><path d="M89.357 26.426v-3.2h1.012l.608 2.182.6-2.182h1.015v3.2h-.628v-2.518l-.665 2.518h-.651l-.663-2.518v2.518z" data-name="Path 14"/></g></g></svg>,
};
